version: '3.8'

networks:
  pr:
    name: pr_prod
    driver: bridge

volumes:
  vredis:
    driver: local

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: pr-backend
    env_file:
      - ./.env
    restart: unless-stopped
    ports:
      - "8080:3000"
    logging:
      driver: 'json-file'
      options:
        max-size: '10M'
        max-file: '5'
    networks:
      - pr
